# Naive Baiyes

PCA

In [2]:
from numpy import array
from sklearn.decomposition import PCA
A = array([[1,2],[3,4],[5,6]])
print(A)
pca=PCA(2)
pca.fit(A)
print(pca.components_)
print(pca.explained_variance_)
B=pca.transform(A)
print(B)

#used in data science work for reducing the dataset with its dimensions

[[1 2]
 [3 4]
 [5 6]]
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
[8. 0.]
[[-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]]


Naive Baiyes

K-means